var data = {
    "publications":
    [
        // {
        //     "highlight": true,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
        {
            "highlight": true,
            "img": "images/FR2Seg.png",
            "title": "FR2Seg: Continual Segmentation Across Multiple Sites via Fourier Style Replay and Adaptive Consistency Regularization",
            "authors": "Cheng Xu, Weiwen Zhang, Hongrui Zhang, Xuemiao Xu, Huaidong Zhang, Jing Zou, and Jing Qin",
            // "preprint": "arXiv",
            "conference": "The Thirty-Ninth AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2025,
            "arxiv": "",
            "pdf": "https://cschengxu.github.io/",
        },
        {
                "highlight": true,
                "img": "images/Tongue.png",
                "title": "Dr. Tongue: Sign-Oriented Multi-label Detection for Remote Tongue Diagnosis",
                "authors": "Yiliang Chen, Steven SC Ho, Cheng Xu*, Yao Jie Xie, Wing Fai Yeung, Shengfeng He, and Jing Qin",
                "conference": "The Thirty-Ninth AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
                "year": 2025,
                "pdf": "https://cschengxu.github.io/",
                "github": "",
            },
        {
            "highlight": false,
            "img": "images/Tongue.png",
            "title": "SCJD: Sparse Correlation and Joint Distillation for Efficient 3D Human Pose Estimation",
            "authors": "Weihong Chen, Xuemiao Xu, Haoxin Yang, Yi Xie, Peng Xiao, Cheng Xu, Huaidong Zhang, and Pheng-Ann Heng",
            "conference": "IEEE International Conference on Multimedia\&Expo 2025 (<b>ICME</b>)",
            "year": 2025,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },

        {
            "highlight": true,
            "img": "images/Dance.png",
            "title": "Beat-It: Beat-Synchronized Multi-Condition 3D Dance Generation",
            "authors": "Zikai Huang, Xuemiao Xu, Cheng Xu*, Huaidong Zhang, Chenxi Zheng, Jing Qin, and Shengfeng He",
            "conference": "The European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "oral": "Oral, 2.0%",
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },

        {
            "highlight": true,
            "img": "images/Portrait_shadow.png",
            "title": "Portrait Shadow Removal via Self-Exemplar Illumination Equalization",
            "authors": "Qian Huang#, Cheng Xu#, Guiqing Li, Ziheng Wu, Shengxin Liu, and Shengfeng He",
            // "preprint": "arXiv",
            "conference": "The 32nd ACM International Conference on Multimedia (<b>ACM MM</b>)",
            "year": 2024,
            "oral": "Oral, 3.97%",
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },

        {
            "highlight": false,
            "img": "images/Portrait_shadow.png",
            "title": "Exploiting Multi-View Clues for Context-Aware Unified Lumbar MRI Identification and Diagnosis",
            "authors": "Weiwen Zhang#, Cheng Xu#, Xuemiao Xu, Huaidong Zhang, Rongchen Zhao, and Jing Qin",
            // "preprint": "arXiv",
            "conference": "2024 International Joint Conference on Neural Networks (<b>IJCNN</b>)",
            "year": 2024,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/CIRI.png",
            "title": "CIRI: Curricular Inactivation for Residue-aware One-shot Video Inpainting",
            "authors": "Weiying Zheng#, Cheng Xu#, Xuemiao Xu, Wenxi Liu, and Shengfeng He",
            "conference": "International Conference on Computer Vision (<b>ICCV</b>)",
            "year": 2023,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
            },
        
        {
            "highlight": false,
            "img": "images/Portrait_shadow.png",
            "title": "Spatial-Aware GAN for Instance-Guided Cross-Spectral Face Hallucination",
            "authors": "Wenpeng Xiao, Cheng Xu, Huaidong Zhang, and Xuemiao Xu",
            // "preprint": "arXiv",
            "conference": "Artificial Intelligence: Second CAAI International Conference (<b>CICAI</b>)",
            "year": 2022,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },

        {
            "highlight": false,
            "img": "images/MM2024_QGround.jpg",
            "title": "GDFace: Gated Deformation for Multi-view Face Image Synthesis",
            "authors": "Xuemiao Xu, Keke Li, Cheng Xu, and Shengfeng He",
            "conference": "The Thirty-Fourth AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2020,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },

        // ========================================
        // Journal papers
        // ========================================
        {
            "highlight": true,
            "img": "images/Pointcloud_generalization.png",
            "title": "Rotation-Adaptive Point Cloud Domain Generalization via Intricate Orientation Learning",
            "authors": "Bangzhen Liu, Chenxi Zheng, Xuemiao Xu, Cheng Xu*, Huaidong Zhang, and Shengfeng He",
            "journal": "IEEE Transactions on Pattern Analysis and Machine Intelligence (<b>TPAMI</b>)",
            "year": "2025",
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {   
            "highlight": true,
            "img": "images/Human_rendering.png",
            "title": "Delving into Invisible Semantics for Generalized One-shot Neural Human Rendering",
            "authors": "Yihong Lin, Xuemiao Xu, Huaidong Zhang, Cheng Xu*, Weijie Li, Yi Xie, Jing Qin, and Shengfeng He",
            "journal": "IEEE Transactions on Visualization and Computer Graphics (<b>TVCG</b>)",
            "year": "2025",
            "pdf": "https://cschengxu.github.io/"
        },
        {
            "highlight": true,
            "img": "images/Mix_domain.png",
            "title": "Open-set Mixed Domain Adaptation via Visual-Linguistic Focal Evolving",
            "authors": "Bangzhen Liu, Yangyang Xu, Cheng Xu*, Xuemiao Xu, and Shengfeng He",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": "2025",
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "Towards Label-free Defect Detection in Additive Manufacturing via Dual-classifier Semi-supervised Learning for Vision-language Models",
            "authors": "Kang Wang, Lanqing Liu, Cheng Xu, Jing Zou, Haoneng Lin, Naiyu Fang, and Jingchao Jiang",
            "journal": "Journal of Intelligent Manufacturing (<b>JIMS</b>)",
            "year": 2025,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/Face_anonymization.png",
            "title": "G2Face: High-Fidelity Reversible Face Anonymization via Generative and Geometric Priors",
            "authors": "Haoxin Yang, Xuemiao Xu, Cheng Xu*, Huaidong Zhang, Jing Qin, Yi Wang, Pheng-Ann Heng, and Shengfeng He",
            "journal": "IEEE Transactions on Information Forensics and Security (<b>TIFS</b>)",
            "year": 2024,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "Unambiguous Granularity Distillation for Asymmetric Image Retrieval",
            "authors": "Hongrui Zhang, Yi Xie, Haoquan Zhang, Cheng Xu, Xuandi Luo, Donglei Chen, Xuemiao Xu, Huaidong Zhang, Pheng-Ann Heng, and Shengfeng He",
            "journal": "Neural Networks (<b>NN</b>)",
            "year": 2024,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "IM-Diff: Implicit Multi-contrast Diffusion Model for Arbitrary Scale MRI Super-Resolution",
            "authors": "Lanqing Liu, Jing Zou, Cheng Xu, Kang Wang, Jun Lyu, Xuemiao Xu, Zhanli Hu, and Jing Qin",
            "journal": "Journal of Biomedical and Health Informatics (<b>JBHI</b>)",
            "year": 2024,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "Dual-space High-frequency Learning for Transformer-based MRI Super-resolution",
            "authors": "Haoneng Lin, Jing Zou, Kang Wang, Yidan Feng, Cheng Xu, Jun Lyu, and Jing Qin",
            "journal": "Computer Methods and Programs in Biomedicine (<b>CMPB</b>)",
            "year": 2024,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/Human_synthesis.png",
            "title": "Pose and Attribute Consistent Person Image Synthesis",
            "authors": "Cheng Xu, Zejun Chen, Jiajie Mai, Xuemiao Xu, and Shengfeng He",
            "journal": "ACM Transactions Multimedia Computing, Communications, and Applications (<b>TOMM</b>)",
            "year": 2023,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/Cartoon_animations.png",
            "title": "Multi-scale Flow-based Occluding Effect and Content Separation for Cartoon Animations",
            "authors": "Cheng Xu, Wei Qu, Xuemiao Xu, and Xueting Liu",
            "journal": "IEEE Transactions on Visualization and Computer Graphics (<b>TVCG</b>)",
            "year": "2022",
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/FDFace.png",
            "title": "Fully Deformable Network for Multi-view Face Image Synthesis",
            "authors": "Cheng Xu, Keke Li, Xuandi Luo, Xuemiao Xu, Shengfeng He, and Kun Zhang",
            "journal": "IEEE Transactions on Neural Networks and Learning Systems (<b>TNNLS</b>)",
            "year": 2022,
            "pdf": "https://cschengxu.github.io/",
            "project": "",
        },
        {
            "highlight": true,
            "img": "images/Portrait2Anime.png",
            "title": "Appearance-preserved Portrait-to-anime Translation via Proxy-guided Domain Adaptation",
            "authors": "Wenpeng Xiao#, Cheng Xu#, Jiajie Mai, Xuemiao Xu, Chengze Li, Xueting Liu, and Shengfeng He",
            "journal": "IEEE Transactions on Visualization and Computer Graphics (<b>TVCG</b>)",
            "year": 2022,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "Multi-View Face Synthesis via Progressive Face Flow",
            "authors": "Yangyang Xu, Xuemiao Xu, Jianbo Jiao, Keke Li, Cheng Xu, and Shengfeng He",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2021,
            "pdf": "https://cschengxu.github.io/",
            "github": "",
        }
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
    },
    "author_links":
    {
        "Xuemiao Xu": "https://www2.scut.edu.cn/cs/2017/0629/c22284a328094/page.htm",
        "Shengfeng He": "https://shengfenghe.github.io/",
        "Jing Qin": "https://harry-qinjing.github.io/",
        "Huaidong Zhang": "https://www2.scut.edu.cn/ft/2021/1102/c29779a495444/page.htm",
        "Yangyang Xu":"https://cnnlstm.github.io/",
        "Pheng-Ann Heng":"https://www.cse.cuhk.edu.hk/~pheng/",
        "Xueting Liu":"https://www.sfu.edu.hk/en/schools-and-offices/schools-and-departments/school-of-computing-and-information-sciences/staff-directory/dr-tina-liu-xueting/index.html",
        "Chengze Li":"https://www.sfu.edu.hk/en/schools-and-offices/schools-and-departments/school-of-computing-and-information-sciences/staff-directory/dr-li-chengze/index.html",
    }
};