var data = {
    "publications":
    [
        // {
        //     "highlight": true,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
        {
            "highlight": true,
            "img": "images/FR2Seg.png",
            "title": "FR2Seg: Continual Segmentation Across Multiple Sites via Fourier Style Replay and Adaptive Consistency Regularization",
            "authors": "Cheng Xu, Weiwen Zhang, Hongrui Zhang, Xuemiao Xu, Huaidong Zhang, Jing Zou, Jing Qin",
            // "preprint": "arXiv",
            "conference": "The Thirty-Ninth AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2025,
            "arxiv": "",
            "pdf": "xxxxx",
        },

        {
                "highlight": true,
                "img": "images/Tongue.png",
                "title": "Dr. Tongue: Sign-Oriented Multi-label Detection for Remote Tongue Diagnosis",
                "authors": "Yiliang Chen, Steven SC Ho, Cheng Xu*, Yao Jie Xie, Wing Fai Yeung, Shengfeng He, Jing Qin",
                "conference": "The Thirty-Ninth AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
                "year": 2025,
                "pdf": "xxxxx",
                "github": "",
            },

        {
            "highlight": true,
            "img": "images/Dance.png",
            "title": "Beat-It: Beat-Synchronized Multi-Condition 3D Dance Generation",
            "authors": "Zikai Huang, Xuemiao Xu, Cheng Xu*, Huaidong Zhang, Chenxi Zheng, Jing Qin, Shengfeng He",
            "conference": "The European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "oral": "Oral, 2.0%",
            "pdf": "xxxxx",
            "github": "",
        },

        {
            "highlight": true,
            "img": "images/Portrait_shadow.png",
            "title": "Portrait Shadow Removal via Self-Exemplar Illumination Equalization",
            "authors": "Qian Huang#, Cheng Xu#, Guiqing Li, Ziheng Wu, Shengxin Liu, Shengfeng He",
            // "preprint": "arXiv",
            "conference": "The 32nd ACM International Conference on Multimedia (<b>ACM MM</b>)",
            "year": 2024,
            "oral": "Oral, 3.97%",
            "pdf": "xxxxx",
            "github": "",
        },

        {
            "highlight": true,
            "img": "images/CIRI.png",
            "title": "CIRI: Curricular Inactivation for Residue-aware One-shot Video Inpainting",
            "authors": "Weiying Zheng#, Cheng Xu#, Xuemiao Xu, Wenxi Liu, and Shengfeng He",
            "conference": "International Conference on Computer Vision (<b>ICCV</b>)",
            "year": 2023,
            "pdf": "xxxxx",
            "github": "",
            },

        {
            "highlight": false,
            "img": "images/MM2024_QGround.jpg",
            "title": "GDFace: Gated Deformation for Multi-view Face Image Synthesis",
            "authors": "Xuemiao Xu, Keke Li, Cheng Xu, and Shengfeng He",
            "conference": "The Thirty-Fourth AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "year": 2020,
            "pdf": "xxxxx",
            "github": "",
        },

        // ========================================
        // Journal papers
        // ========================================
        {
            "highlight": true,
            "img": "images/Pointcloud_generalization.png",
            "title": "Rotation-Adaptive Point Cloud Domain Generalization via Intricate Orientation Learning",
            "authors": "Bangzhen Liu, Chenxi Zheng, Xuemiao Xu, Cheng Xu*, Huaidong Zhang, Shengfeng He",
            "journal": "IEEE Transactions on Pattern Analysis and Machine Intelligence (<b>TPAMI</b>)",
            "year": "2025",
            "pdf": "xxxxx",
            "github": "",
        },
        {   
            "highlight": true,
            "img": "images/Human_rendering.png",
            "title": "Delving into Invisible Semantics for Generalized One-shot Neural Human Rendering",
            "authors": "Yihong Lin, Xuemiao Xu, Huaidong Zhang, Cheng Xu*, Weijie Li, Yi Xie, Jing Qin, Shengfeng He",
            "journal": "IEEE Transactions on Visualization and Computer Graphics (<b>TVCG</b>)",
            "year": "2025",
            "pdf": "https://ieeexplore.ieee.org/abstract/document/10235894"
        },
        {
            "highlight": true,
            "img": "images/Mix_domain.png",
            "title": "Open-set Mixed Domain Adaptation via Visual-Linguistic Focal Evolving",
            "authors": "Bangzhen Liu, Yangyang Xu, Cheng Xu*, Xuemiao Xu, Shengfeng He",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": "2025",
            "pdf": "xxxxx",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/Face_anonymization.png",
            "title": "G2Face: High-Fidelity Reversible Face Anonymization via Generative and Geometric Priors",
            "authors": "Haoxin Yang, Xuemiao Xu, Cheng Xu*, Huaidong Zhang, Jing Qin, Yi Wang, Pheng-Ann Heng, Shengfeng He",
            "journal": "IEEE Transactions on Information Forensics and Security (<b>TIFS</b>)",
            "year": "2024",
            "pdf": "xxxxx",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/Human_synthesis.png",
            "title": "Pose and Attribute Consistent Person Image Synthesis",
            "authors": "Cheng Xu, Zejun Chen, Jiajie Mai, Xuemiao Xu, and Shengfeng He",
            "journal": "ACM Transactions Multimedia Computing, Communications, and Applications (<b>TOMM</b>)",
            "year": 2023,
            "pdf": "xxxxx",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/Cartoon_animations.png",
            "title": "Multi-scale Flow-based Occluding Effect and Content Separation for Cartoon Animations",
            "authors": "Cheng Xu, Wei Qu, Xuemiao Xu, and Xueting Liun",
            "journal": "IEEE Transactions on Visualization and Computer Graphics (<b>TVCG</b>)",
            "year": "2022",
            "pdf": "xxxxx",
            "github": "",
        },
        {
            "highlight": true,
            "img": "images/FDFace.png",
            "title": "Fully Deformable Network for Multi-view Face Image Synthesis",
            "authors": "Cheng Xu, Keke Li, Xuandi Luo, Xuemiao Xu, Shengfeng He, and Kun Zhang",
            "journal": "IEEE Transactions on Neural Networks and Learning Systems (<b>TNNLS</b>)",
            "year": 2022,
            "pdf": "xxxxx",
            "project": "",
        },
        {
            "highlight": true,
            "img": "images/Portrait2Anime.png",
            "title": "Appearance-preserved Portrait-to-anime Translation via Proxy-guided Domain Adaptation",
            "authors": "Wenpeng Xiao#, Cheng Xu#, Jiajie Mai, Xuemiao Xu, Chengze Li, Xueting Liu, and Shengfeng He",
            "journal": "IEEE Transactions on Visualization and Computer Graphics (<b>TVCG</b>)",
            "year": 2022,
            "pdf": "xxxxx",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "IM-Diff: Implicit Multi-contrast Diffusion Model for Arbitrary Scale MRI Super-Resolution",
            "authors": "Lanqing Liu, Jing Zou, Cheng Xu, Kang Wang, Jun Lyu, Xuemiao Xu, Zhanli Hu, Jing Qin",
            "journal": "Journal of Biomedical and Health Informatics (<b>JBHI</b>)",
            "year": 2024,
            "pdf": "xxxxx",
            "github": "",
        },
        {
            "highlight": false,
            "img": "images/TIP2020_SPARNet.png",
            "title": "Multi-View Face Synthesis via Progressive Face Flow",
            "authors": "Yangyang Xu, Xuemiao Xu, Jianbo Jiao, Keke Li, Cheng Xu, and Shengfeng He",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2023,
            "pdf": "xxxxx",
            "github": "",
        }
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
    },
    "author_links":
    {
        "Kwan-Yee K. Wong": "http://www.cs.hku.hk/~kykwong",
        "Liang Liao": "https://liaoliang92.github.io/homepage/",
        "Xiaoming Li": "https://csxmli2016.github.io/",
        "Haoning Wu": "http://teowu.github.io/",
        "Weisi Lin": "https://personal.ntu.edu.sg/wslin/Home.html",
        "Lei Zhang": "http://www4.comp.polyu.edu.hk/~cslzhang/",
        "Guanying Chen": "https://guanyingc.github.io/",
        "Zhenfang Chen": "http://zfchenunique.github.io/",
        "Wenqi Yang": "https://ywq.github.io/",
        "Wangmeng Zuo": "http://homepage.hit.edu.cn/wangmengzuo",
        "Shangchen Zhou": "https://shangchenzhou.com/",
        "Lingbo Yang": "http://lotayou.github.io/",
        "Xiaoguang Han": "https://mypage.cuhk.edu.cn/academics/hanxiaoguang/",
        "Chunyi Li": "http://lcysyzxdxc.github.io/",
        "Guangtao Zhai": "https://faculty.sjtu.edu.cn/zhaiguangtao/en/index.htm",
        "Zicheng Zhang": "https://github.com/zzc-1998",
        "Yipeng Qin": "https://www.cardiff.ac.uk/people/view/1508897-qin-yipeng",
        "Jinwei Gu": "http://www.gujinwei.org/",
        "Yuming Fang": "https://sites.google.com/site/leofangyuming/",
        "Shaozheng Hao": "https://haoosz.github.io/",
        "Mengcheng Lan": "https://mc-lan.github.io/",
        "Wenxiu Sun": "http://wenxiusun.com/",
        "Weixia Zhang": "https://sites.google.com/view/r-panda",
        "Yixuan Gao": "https://github.com/YixuanGao98",
        "Annan Wang": "https://github.com/AnnanWangDaniel",
        "Erli Zhang": "https://github.com/ZhangErliCarl/",
        "Qiong Yan": "https://scholar.google.com/citations?user=uT9CtPYAAAAJ&hl=en",
        "Xiongkuo Min": "https://sites.google.com/site/minxiongkuo/",
        "Jingwen Hou": "https://scholar.google.com.sg/citations?user=NlNOyiQAAAAJ&hl=zh-CN",
        "Tao Yang": "https://github.com/yangxy",
        "Shihui Guo": "https://scholar.google.co.uk/citations?user=RPAVxiAAAAAJ&hl=en",
        "Xinyu Shi": "https://xinyu-shi.github.io/",
    }
};